### ISSUE TITLE
error on Version opencart  2.1.0.2

### ISSUE THREAD

**Issue by MuhamedAuda** [payfort/opencart#5]
Hi,
I installed it before on many opencart and work successfully, but on OC Ver 2.1.0.2 when click + install give me this:
Notice: Error: Could not load model /home/mokab/public_html/admin/model/setting/extension.php! in /home/mokab/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 63

and it installed and after click edit, it show tow pages of errors massages !!

**Comment by alovak** [comment]
Hi @MuhamedAuda!

Can it be a problem with permissions?

**Comment by MuhamedAuda** [comment]
@alovak 
No, I checked permissions and made a refresh ..
