### ISSUE TITLE
No popup window for cc details

### ISSUE THREAD

**Issue by creativient** [payfort/opencart#6]
May I ask for your help since the exentension for Payfort Start is not working in our front end? Once we are at the payment method after choosing debit/credit card payment, there is no pop-up window.
Opencart Version 2.1.0.2

**Comment by alovak** [comment]
@creativient have you checked 't&c' and pressed 'Continue'?

do you have a custom theme?
any errors in console log?

**Comment by creativient** [comment]
yes, custome theme.. pavotheme. our website is www.officecentre.ae
No errors on console logs.

**Comment by creativient** [comment]
i check again.. there is no popup window for payment after i tick the box for T&C and click continue. No popup window.. it went directly to confirm order.

**Comment by alovak** [comment]
@creativient I guess it can be due to 2.1 not 2.0. Do you have php devs who can find where the issue is?

**Comment by creativient** [comment]
we can't really find the  issue though..

**Comment by alovak** [comment]
@creativient I think the problem can be with https://github.com/vqmod/vqmod

can you please check this document (re-install vqmod, clean cache folder, etc.) https://github.com/vqmod/vqmod/wiki/Troubleshooting

let me know if it helps

**Comment by creativient** [comment]
it didin't help at all. would you mind if i share access for you to check? please give me your email address. thanks

**Comment by shamskaramat** [comment]
Got the same issue with opencart 2. There is no popup to enter credit card details. creativient can you please let me know the solution you applied?

**Comment by shamskaramat** [comment]
Got it working with opencart version 2.0.1.0.

**Comment by usernamecopied** [comment]
I have the same issue for opencart v 2.1.0.2. There is no popup. Can someone please guide me? I cannot use opencart version 2.0.x as my project is almost done now.
