### ISSUE TITLE
PayFort Start Error "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data OK"

### ISSUE THREAD

**Issue by shamskaramat** [payfort/opencart#7]
When try to checkout using CreditCard with PayFort, a popup appears with JSON error ... "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data OK".

Any ideas please?

**Comment by alovak** [comment]
Hi! Please, look into server / php logs to find where is the error.

**Comment by shamskaramat** [comment]
Thanks Alovak for your contribution. I checked the logs and there are no clues at all. I checked the same installation at different server as well but same error. Anyone has any idea?

**Comment by alovak** [comment]
I can guess that his is due to this line:

https://github.com/payfort/opencart/blob/6699686987238ca0287b93d72bc552f6810f4986/upload/catalog/controller/payment/start_payments.php#L42

file should be read from local path

```
$currency_json_data = json_decode(file_get_contents(XXXX. '/data/currencies.json'), 1);
```
where XXX is the path to /data/currencies.json

**Comment by shamskaramat** [comment]
It is not helping at all.. THERE IS NO POPUP SHOWING AT ALL WHEN WE SELECT CREDIT CARD... Please check here www.bouquetward-dxb.com. I checked the same plugin you supplied on 4 different servers and all having the same issue. So there must be something with the plugin. Can you please check?

**Comment by smgom** [comment]
Hey there is nothing wrong with the plugin, it might be some custom theme
issue.
Also please email me your details: Manish95611@gmail.com

**Comment by shamskaramat** [comment]
Thanks Smgom.. I even checked in the default theme. Same issue.

**Comment by smgom** [comment]
Is vqmod working ? Also  what is the opencart version you are using?

Can you send me your vqcache folder?

On Mon, 6 Feb 2017 at 9:30 AM, Shams Karamat <notifications@github.com>
wrote:

Thanks Smgom.. I even checked in the default theme. Same issue.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/payfort/opencart/issues/7#issuecomment-277581855>, or mute
the thread

**Comment by shamskaramat** [comment]
Thanks Smgom. Finally got the solution. OpenCart Version 2.3 is not supported at all. I went back to 2.0.1.0 and everything works. Thanks for your input.
